# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='标题')),
                ('beautified_url', models.TextField(null=True, verbose_name='美化URL')),
                ('article_id', models.IntegerField(verbose_name='文章id')),
                ('content', models.TextField(null=True, verbose_name='内容')),
                ('content_type', models.CharField(default='m', max_length=2, verbose_name='内容类型')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(default='d', max_length=2, verbose_name='文章状态')),
                ('visibility', models.CharField(default='p', max_length=2, verbose_name='可见性')),
                ('hash', models.CharField(max_length=20, null=True, verbose_name='文章hash code')),
                ('top', models.BooleanField(default=False, verbose_name='是否置顶')),
            ],
            options={
                'ordering': ['article_id', '-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='配置名称')),
                ('value', models.TextField(null=True, verbose_name='值')),
            ],
        ),
        migrations.CreateModel(
            name='Res_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_created=True)),
                ('resid', models.CharField(max_length=40, verbose_name='资源id')),
                ('type', models.TextField(verbose_name='类型，尺寸，分辨率等')),
                ('uri', models.TextField(verbose_name='资源uri')),
                ('name', models.TextField(verbose_name='资源标题')),
                ('note', models.TextField(null=True, verbose_name='说明')),
                ('replace_text', models.TextField(null=True, verbose_name='替代文字')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Tag'),
        ),
    ]
